version: '3.8'
services:
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: npm run start:dev users
    env_file:
      - ./apps/users/.env
    depends_on:
      users-db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app:delegated
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    networks:
      - app-network
    develop:
      watch:
        - path: ./apps/users/src
          action: sync
          target: /usr/src/app/apps/users/src
        - path: ./package.json
          action: rebuild
        

  users-db:
    image: postgres:13
    env_file:
      - ./apps/users/.env
    ports:
      - '5434:5432'  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  users-test-db:
    image: postgres:13
    env_file:
      - ./apps/users/.env
    ports:
      - '5435:5432'  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
networks:
  app-network:  # Define the custom network
    driver: bridge  # Use the default bridge driver for local networking