apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: traefik
  creationTimestamp: "2024-10-10T21:49:51Z"
  labels:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-20.8.0
  name: traefik
  namespace: traefik
  resourceVersion: "90954"
  uid: 688ac179-30d7-4073-baae-a0dfe93a6fe2
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.99.13
  clusterIPs:
  - 10.96.99.13
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    nodePort: 30183
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 32593
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
